"""
GET /api/crowd — Real-time crowd analysis and AI-generated alerts.

Combines live zone data with either Gemini-powered or rule-based
crowd management recommendations for stadium staff.
"""

from __future__ import annotations

import logging
from typing import Literal, cast, get_type_hints

from fastapi import APIRouter, Request

from app.core.config import get_settings
from app.core.rate_limit import CROWD_LIMIT, limiter
from app.models.stadium import CrowdAnalysisResponse
from app.services.gemini_service import GeminiUnavailableError, generate_crowd_alerts
from app.services.stadium_data import (
    STADIUM_CAPACITY,
    get_operations_brief,
    get_rule_based_alerts,
    get_total_attendance,
    get_zone_statuses,
)

logger = logging.getLogger(__name__)

router = APIRouter(tags=["Crowd"])


@limiter.limit(CROWD_LIMIT)
async def get_crowd_analysis(request: Request) -> CrowdAnalysisResponse:
    """
    Get real-time crowd analysis with AI-generated alerts.

    Rate limited to 30 requests/minute per IP.
    """
    settings = get_settings()
    zones = get_zone_statuses()
    total = get_total_attendance(zones)

    source: str

    if settings.USE_GEMINI:
        try:
            alerts = await generate_crowd_alerts(zones)
            source = "gemini"
            logger.info("Crowd alerts generated by Gemini (%d alerts)", len(alerts))
        except GeminiUnavailableError as exc:
            logger.warning("Gemini unavailable for crowd analysis, falling back: %s", exc)
            alerts = get_rule_based_alerts(zones)
            source = "rules"
    else:
        alerts = get_rule_based_alerts(zones)
        source = "rules"

    return CrowdAnalysisResponse(
        zones=zones,
        alerts=alerts,
        total_attendance=total,
        stadium_capacity=STADIUM_CAPACITY,
        overall_occupancy_pct=round(total / STADIUM_CAPACITY * 100, 1),
        source=cast(Literal["gemini", "rules"], source),
        operations_brief=get_operations_brief(zones, alerts),
    )


# Resolve annotations
get_crowd_analysis.__annotations__ = get_type_hints(get_crowd_analysis)
if hasattr(get_crowd_analysis, "__wrapped__"):
    get_crowd_analysis.__wrapped__.__annotations__ = get_type_hints(
        get_crowd_analysis.__wrapped__
    )

router.add_api_route(
    "/crowd",
    endpoint=get_crowd_analysis,
    methods=["GET"],
    response_model=CrowdAnalysisResponse,
    summary="Crowd analysis dashboard",
    description=(
        "Get real-time zone occupancy data and AI-generated crowd management alerts. "
        "Uses Gemini (primary) with automatic fallback to rule-based analysis."
    ),
)
